version: 2.1

jobs:
  build:
    docker:
      - image: amazoncorretto:17.0.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Set up Java
          command: |
            java -version

      - run:
          name: Build the project
          command: mvn clean install -DskipTests=true

      - run:
          name: Run tests
          command: mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build:
    jobs:
      - build
